<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net48</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Machine.Specifications" />
    <PackageReference Include="Machine.Fakes.FakeItEasy" />
    <PackageReference Include="Machine.Specifications.Runner.Console" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SemanticQuantities\Timtek.SemanticQuantities.csproj" />
  </ItemGroup>
</Project>
